# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT/interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openObjPB = QtWidgets.QPushButton(self.centralwidget)
        self.openObjPB.setGeometry(QtCore.QRect(0, 0, 141, 31))
        self.openObjPB.setObjectName("openObjPB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 80, 1080, 720))
        self.label.setMinimumSize(QtCore.QSize(1080, 720))
        self.label.setMaximumSize(QtCore.QSize(1080, 720))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(380, 0, 817, 42))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.FOVdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.FOVdoubleSpinBox.setObjectName("FOVdoubleSpinBox")
        self.horizontalLayout.addWidget(self.FOVdoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.NearPlaneDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.NearPlaneDoubleSpinBox.setObjectName("NearPlaneDoubleSpinBox")
        self.horizontalLayout.addWidget(self.NearPlaneDoubleSpinBox)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.FarPlaneDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.FarPlaneDoubleSpinBox.setObjectName("FarPlaneDoubleSpinBox")
        self.horizontalLayout.addWidget(self.FarPlaneDoubleSpinBox)
        self.AntialiasingCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.AntialiasingCheckBox.setObjectName("AntialiasingCheckBox")
        self.horizontalLayout.addWidget(self.AntialiasingCheckBox)
        self.FullPolygonsCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.FullPolygonsCheckBox.setObjectName("FullPolygonsCheckBox")
        self.horizontalLayout.addWidget(self.FullPolygonsCheckBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1206, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openObjPB.setText(_translate("MainWindow", "Открыть модель"))
        self.label_2.setText(_translate("MainWindow", "FOV:"))
        self.label_3.setText(_translate("MainWindow", "Near_plane:"))
        self.label_4.setText(_translate("MainWindow", "Far_plane:"))
        self.AntialiasingCheckBox.setText(_translate("MainWindow", "Сглаживание"))
        self.FullPolygonsCheckBox.setText(_translate("MainWindow", "Полные полигоны\n"
"(влияет на FPS)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
